title: RDMkit
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: ""
# this appears on the top navigation bar next to the home button

description: "Find the answers to your Research Data Management questions in Life Sciences."
# Metadata description of the website

remote_theme: ELIXIR-Belgium/jekyll-bootstrap-theme

gtag: G-RXQ55EFTTH
# Google analytics tag

dsw_deep_link_prefix: https://researchers.ds-wizard.org/knowledge-models/dsw:root:latest/preview?questionUuid=
# prefix for DSW deep links to a certain question

navbar:
  theme: dark
  # Can be light, dark, white, primary, secondary

footer:
  background: dark
  # Can be light, dark, white, primary, secondary
  font: white
  # Can be light, dark, white, primary, secondary

theme_color: c23669


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename:output_ext
      layout: "page"
      sidebar: main
      topnav: topnav
      search_exclude: false
  -
    scope:
      path: "pages/data_life_cycle"
    values:
      type: data_life_cycle
  -
    scope:
      path: "pages/your_domain"
    values:
      type: your_domain
  -
    scope:
      path: "pages/your_tasks"
    values:
      type: your_tasks
  -
    scope:
      path: "pages/your_role"
    values:
      type: your_role
  -
    scope:
      path: "pages/tool_assembly"
    values:
      type: tool_assembly
  -
    scope:
      path: "pages/national_resources"
    values:
      type: national_resources
      datatable: true
